<?php
// $Id: xoops_version.php,v 1.5 2007/07/23 04:44:52 nobu Exp $
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion = array('name' => _MI_CCENTER_NAME,
		    'version' => 0.71,
		    'description' => _MI_CCENTER_DESC,
		    'credits' => "Nobuhiro Yasutomi",
		    'author' => "Nobuhiro Yasutomi",
		    'help' => "help.html",
		    'license' => "GPL see LICENSE",
		    'official' => 0,
		    'image' => "ccenter_slogo.png",
		    'dirname' => basename(dirname(__FILE__)));

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][] = "ccenter_form";
$modversion['tables'][] = "ccenter_message";

// OnUpdate - upgrade DATABASE 
//$modversion['onUpdate'] = "onupdate.php";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Menu
$modversion['hasMain'] = 1;
global $xoopsUser;
if (!empty($xoopsUser)) {
    $modversion['sub'][]=array('name'=>_MI_CCENTER_YOURCONTACT,
			       'url'=>"list.php");
    $modversion['sub'][]=array('name'=>_MI_CCENTER_STAFFDESK,
			       'url'=>"reception.php");
}

// Templates
$modversion['templates'][1] =
    array('file' => 'ccenter_index.html',
	  'description' => _MI_CCENTER_FORM_TPL);
$modversion['templates'][] =
    array('file' => 'ccenter_form.html',
	  'description' => _MI_CCENTER_FORM_TPL);
$modversion['templates'][] =
    array('file' => 'ccenter_confirm.html',
	  'description' => _MI_CCENTER_CONF_TPL);
$modversion['templates'][] =
    array('file' => 'ccenter_list.html',
	  'description' => _MI_CCENTER_LIST_TPL);
$modversion['templates'][] =
    array('file' => 'ccenter_message.html',
	  'description' => _MI_CCENTER_MSGS_TPL);
$modversion['templates'][] =
    array('file' => 'ccenter_reception.html',
	  'description' => _MI_CCENTER_RECEPT_TPL);
/*
$modversion['templates'][] =
    array('file' => 'memberdirs_preference.html',
	  'description' => '');
*/

// Blocks
$modversion['blocks'][1]=array('file' => 'ccenter_receipt.php',
			      'name' => _MI_CCENTER_BLOCK_RECEIPT,
			      'description' => '',
			      'clone' => true,
			      'show_func' => "b_ccenter_receipt_show",
			      'edit_func' => "b_ccenter_receipt_edit",
			      'template' => 'ccenter_block_receipt.html',
			      'options' => '-,a,b,c|5');
/*
$modversion['blocks'][]=array('file' => 'memberdirs_index.php',
			      'name' => _MI_CCENTER_BLOCK_INDEX."2",
			      'description' => '',
			      'clone' => true,
			      'show_func' => "b_memberdirs_index_show",
			      'edit_func' => "b_memberdirs_index_edit",
			      'template' => 'memberdirs_block_index.html',
			      'options' => '2');

$modversion['blocks'][]=array('file' => 'memberdirs_search.php',
			      'name' => _MI_CCENTER_BLOCK_SEARCH,
			      'description' => '',
			      'show_func' => "b_memberdirs_search_show",
			      'edit_func' => "b_memberdirs_search_edit",
			      'template' => 'memberdirs_block_search.html');

$modversion['blocks'][]=array('file' => 'memberdirs_avatar.php',
			      'name' => _MI_CCENTER_BLOCK_AVATAR,
			      'description' => '',
			      'show_func' => "b_memberdirs_avatar_show",
			      'edit_func' => "b_memberdirs_avatar_edit",
			      'template' => 'memberdirs_block_avatar.html');

$modversion['blocks'][]=array('file' => 'memberdirs_myavatar.php',
			      'name' => _MI_CCENTER_BLOCK_MYAVATAR,
			      'description' => '',
			      'show_func' => "b_memberdirs_myavatar_show",
			      'edit_func' => "b_memberdirs_myavatar_edit",
			      'template' => 'memberdirs_block_myavatar.html');
*/
// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'message.php';
$modversion['comments']['itemName'] = 'id';

// Comment callback functions
$modversion['comments']['callbackFile'] = 'comment_functions.php';
$modversion['comments']['callback']['approve'] = 'ccenter_com_approve';
$modversion['comments']['callback']['update'] = 'ccenter_com_update';

// Config

$modversion['hasconfig'] = 1;
$modversion['config'][]=array(
    'name' => 'max_lists',
    'title' => '_MI_CCENTER_LISTS',
    'description' => '_MI_CCENTER_LISTS_DESC',
    'formtype' => 'select',
    'valuetype' => 'int',
    'default' => 25,
    'options' => array(5=>5,10=>10,25=>25,50=>50,100=>100,200=>200,500=>500,1000=>1000)
    );
$modversion['config'][]=array('name' => 'def_attrs',
			      'title' => '_MI_CCENTER_DEF_ATTRS',
			      'description' => '_MI_CCENTER_DEF_ATTRS_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'string',
			      'default' => 'size=60,rows=5,cols=50');
/*
$modversion['config'][]=array('name' => 'search_list',
			      'title' => '_MI_CCENTER_SEARCH',
			      'description' => '_MI_CCENTER_SEARCH_DESC',
			      'formtype' => 'textarea',
			      'valuetype' => 'string',
			      'default' => _MI_CCENTER_SEARCH_DEF);
$modversion['config'][]=array('name' => 'max_avatar',
			      'title' => '_MI_CCENTER_MAX_AVATAR',
			      'description' => '_MI_CCENTER_MAX_AVATAR_DSC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 6);
$modversion['config'][]=array('name' => 'contact_form',
			      'title' => '_MI_CCENTER_CONTACT',
			      'description' => '_MI_CCENTER_CONTACT_DESC',
			      'formtype' => 'textarea',
			      'valuetype' => 'string',
			      'default' => _MI_CCENTER_CONTACT_DEF);
$modversion['config'][]=array('name' => 'contact_uri',
			      'title' => '_MI_CCENTER_CONTACTURI',
			      'description' => '_MI_CCENTER_CONTACTURI_DSC',
			      'formtype' => 'text',
			      'valuetype' => 'string',
			      'default' => '');
$modversion['config'][]=array('name' => 'contact_mail',
			      'title' => '_MI_CCENTER_CONTACTML',
			      'description' => '_MI_CCENTER_CONTACTML_DSC',
			      'formtype' => 'yesno',
			      'valuetype' => 'int',
			      'default' => 1);
$modversion['config'][]=array('name' => 'avatar',
			      'title' => '_MI_CCENTER_AVATAR',
			      'description' => '_MI_CCENTER_AVATAR_DESC',
			      'formtype' => 'textarea',
			      'valuetype' => 'string',
			      'default' => _MI_CCENTER_AVATAR_DEF);
$modversion['config'][]=array('name' => 'avatar_form',
			      'title' => '_MI_CCENTER_AVATARFORM',
			      'description' => '_MI_CCENTER_AVATARFORM_DSC',
			      'formtype' => 'textarea',
			      'valuetype' => 'string',
			      'default' => _MI_CCENTER_AVATARFORM_DEF);
$modversion['config'][]=array('name' => 'avatar_uri',
			      'title' => '_MI_CCENTER_AVATAR_URI',
			      'description' => '_MI_CCENTER_AVATAR_URI_DSC',
			      'formtype' => 'text',
			      'valuetype' => 'string',
			      'default' => '');
$modversion['config'][]=array('name' => 'avatar_mail',
			      'title' => '_MI_CCENTER_AVATARML',
			      'description' => '_MI_CCENTER_AVATARML_DSC',
			      'formtype' => 'yesno',
			      'valuetype' => 'int',
			      'default' => 1);
$modversion['config'][]=array('name' => 'pref_form',
			      'title' => '_MI_CCENTER_PREFFORM',
			      'description' => '_MI_CCENTER_PRIFFORM_DSC',
			      'formtype' => 'textarea',
			      'valuetype' => 'string',
			      'default' => _MI_CCENTER_PREFFORM_DEF);
$modversion['config'][]=array('name' => 'notice',
			      'title' => '_MI_CCENTER_NOTICE',
			      'description' => '_MI_CCENTER_NOTICE_DESC',
			      'formtype' => 'textarea',
			      'valuetype' => 'string',
			      'default' => _MI_CCENTER_NOTICE_DEF);
*/
// Notification

$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'notification.inc.php';
$modversion['notification']['lookup_func'] = 'ccenter_notify_iteminfo';

$modversion['notification']['category'][1] =
    array('name' => 'global',
	  'title' => _MI_CCENTER_GLOBAL_NOTIFY,
	  'description' => '',
	  'subscribe_from' => array('reception.php')
	);
$modversion['notification']['category'][] =
    array('name' => 'form',
	  'title' => _MI_CCENTER_FORM_NOTIFY,
	  'item_name' => 'form',
	  'description' => '',
	  'subscribe_from' => array('reception.php')
	);
$modversion['notification']['category'][] =
    array('name' => 'message',
	  'title' => _MI_CCENTER_MESSAGE_NOTIFY,
	  'description' => '',
	  'item_name' => 'id',
	  'subscribe_from' => array('message.php')
	);
$modversion['notification']['event'][1]=
    array('name' => 'new',
	  'category' => 'global',
	  'admin_only'=>1,
	  'title' => _MI_CCENTER_NEWPOST_NOTIFY,
	  'caption' => _MI_CCENTER_NEWPOST_NOTIFY_CAP,
	  'description' => '',
	  'mail_template' => 'notify',
	  'mail_subject' => _MI_CCENTER_NEWPOST_SUBJECT);
$modversion['notification']['event'][]=
    array('name' => 'new',
	  'category' => 'form',
	  'admin_only'=>1,
	  'title' => _MI_CCENTER_NEWPOST_NOTIFY,
	  'caption' => _MI_CCENTER_NEWPOST_NOTIFY_CAP,
	  'description' => '',
	  'mail_template' => 'notify',
	  'mail_subject' => _MI_CCENTER_NEWPOST_SUBJECT);
/*
$modversion['notification']['event'][1]=
    array('name' => 'new',
	  'category' => 'form',
	  'admin_only'=>1,
	  'title' => _MI_CCENTER_NEWPOSTFORM_NOTIFY,
	  'caption' => _MI_CCENTER_NEWPOSTFORM_NOTIFY_DESC,
	  'description' => '',
	  'mail_template' => 'notify',
	  'mail_subject' => _MI_CCENTER_NEWPOST_SUBJECT);
*/
?>